### ISSUE TITLE
1일차 Project

### ISSUE THREAD

**Issue by seungb5** [seungb5/TMDB-Box-office-Prediction#9]
팀 구성
sb : base model 작성, 
gm : base 모델 탐색
sb : EDA, FE
dm : EDA, FE
dy : TMDB API, 실제 수익률 예측

할 일
- 일별 작업 내용 공유 및 발표
- 작업 내용 공유 / 운영

**Comment by seungb5** [comment]
sb, dm : EDA, FE

**Comment by seungb5** [comment]
변수 설명

데이터 설명 id - 각 영화의 정수 고유 ID

belongs_to_collection - JSON 형식의 영화의 TMDB ID, 이름, 영화 포스터 및 배경 URL을 포함합니다. 다음과 같은 포스터 및 배경 이미지를 볼 수 있습니다 : 

예산 : 영화의 예산 (달러). 0 값은 알 수 없음을 의미합니다.

장르 : JSON 형식의 모든 장르 이름 및 TMDB ID를 포함합니다.

홈페이지-영화의 공식 홈페이지 URL을 포함합니다. 예 : http://sonyclassics.com/whiplash/, 이것은 Whiplash 영화의 홈페이지입니다.

imdb_id - 영화의 IMDB id (문자열). 다음과 같이 IMDB 페이지를 방문 할 수 있습니다 : https://www.imdb.com/title/

original_language - 영화가 만들어진 원래 언어의 두 자릿수 코드입니다. 좋아요 : en = 영어, fr = 프랑스어.

original_title - 영화의 원래 제목. 원 제목이 영어가 아닌 경우 제목과 원 제목이 다를 수 있습니다.

개요 - 영화에 대한 간략한 설명.

인기 - 플로트에서 영화의 인기.

poster_path - 영화의 포스터 경로입니다. 다음과 같은 전체 이미지를 볼 수 있습니다 : https://image.tmdb.org/t/p/original/

production_companies - 영화의 JSON 형식의 모든 제작 회사 이름 및 TMDB ID입니다.

production_countries - JSON 형식의 프로덕션 회사의 두 자리 코드 및 전체 이름입니다.

release_date - mm / dd / yy 형식의 영화 출시 날짜입니다.

런타임 - 동영상의 총 런타임 (분) (정수).

spoken_languages ​​- 두 자리 코드와 말의 성명.

상태 - 영화가 공개되었거나 소문이 났습니까?

tagline - 영화의 태그 라인

제목 - 영화의 영어 제목

키워드 - TMDB Id 및 모든 키워드의 이름 (JSON 형식).

cast - JSON 형식의 모든 TMDB ID, 이름, 문자 이름, 성별 (1 = 여성, 2 = 남성) 변환

승무원 - 이름, TMDB id, Director, Writer, Art, Sound 등과 같은 다양한 종류의 승무원 직업 프로필 경로

수익 - 영화에서 달러로 얻은 총 수익입니다.

**Comment by seungb5** [comment]
[base model](https://www.kaggle.com/samusram/film-industry-curiosities-box-office-prediction
)

**Comment by dodobrain** [comment]
영향을 미치는 변수:genre, homepage, tagline, original title, original_language, spoken_languages,
